project:
  type: website

website:
  repo-url: https://github.com/rafalopezv/webSanturban
  repo-actions: [source]
  title: "Proyecto Santurbán"
  reader-mode: true
  sidebar:
    style: "floating"
    contents:
      - section: "Sobre el proyecto"
        contents:
          - index.qmd
          
      - section: "Resultados"
        contents:
          - extraccion.qmd
          - analisis.qmd
          
      - section: "Sobre la metodología"
        contents:
          - extraccion_met.qmd
      
  navbar:
    background: "#EDFAFD"
    right:
      - icon: github
        href: https://github.com/rafalopezv/webSanturban
      - icon: envelope
        href: mailto:sebastianlopez@usantotomas.edu.co
      - icon: envelope
        href: mailto:lopezvalverde.rafael@gmail.com
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

